# Generated by Django 4.2.16 on 2024-11-20 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ensemble',
            name='slots',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='name',
        ),
        migrations.AddField(
            model_name='ensemble',
            name='num_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slot',
            name='slot_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='slot',
            name='musician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
